//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Symbology {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SymbologyMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SymbologyMessageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Symbology.SymbologyMessageStrings", typeof(SymbologyMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating Shaded Relief 的本地化字符串。
        /// </summary>
        internal static string DesktopRasterExt_CreatingShadedRelief {
            get {
                return ResourceManager.GetString("DesktopRasterExt_CreatingShadedRelief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting color scheme to bitmap. 的本地化字符串。
        /// </summary>
        internal static string DesktopRasterExt_PaintingColorScheme {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting Hillshade To Bitmap 的本地化字符串。
        /// </summary>
        internal static string DesktopRasterExt_PaintingHillshade {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingHillshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据 的本地化字符串。
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少括号 的本地化字符串。
        /// </summary>
        internal static string Expression_ClosingBracket {
            get {
                return ResourceManager.GetString("Expression_ClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式为空 的本地化字符串。
        /// </summary>
        internal static string Expression_Empty {
            get {
                return ResourceManager.GetString("Expression_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式包含空字段 的本地化字符串。
        /// </summary>
        internal static string Expression_EmptyField {
            get {
                return ResourceManager.GetString("Expression_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下字段未找到： 的本地化字符串。
        /// </summary>
        internal static string Expression_FieldNotFound {
            get {
                return ResourceManager.GetString("Expression_FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少左操作数 的本地化字符串。
        /// </summary>
        internal static string Expression_LeftOperandMissing {
            get {
                return ResourceManager.GetString("Expression_LeftOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不是数字 的本地化字符串。
        /// </summary>
        internal static string Expression_NotANumber {
            get {
                return ResourceManager.GetString("Expression_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected operand. Found character {0} at position {1}. 的本地化字符串。
        /// </summary>
        internal static string Expression_OperandExpected {
            get {
                return ResourceManager.GetString("Expression_OperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to find operation. 的本地化字符串。
        /// </summary>
        internal static string Expression_OperationNotFound {
            get {
                return ResourceManager.GetString("Expression_OperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation not supported. 的本地化字符串。
        /// </summary>
        internal static string Expression_OperationNotSupported {
            get {
                return ResourceManager.GetString("Expression_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected operator. Found character {0} at position {1}. 的本地化字符串。
        /// </summary>
        internal static string Expression_OperatorExprected {
            get {
                return ResourceManager.GetString("Expression_OperatorExprected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an operator in place of a value. 的本地化字符串。
        /// </summary>
        internal static string Expression_OpereratorInsteadOfValue {
            get {
                return ResourceManager.GetString("Expression_OpereratorInsteadOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + operation isn&apos;t allowed for boolean values. 的本地化字符串。
        /// </summary>
        internal static string Expression_PlusNotAllowed {
            get {
                return ResourceManager.GetString("Expression_PlusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No right operand was found. 的本地化字符串。
        /// </summary>
        internal static string Expression_RightOperandMissing {
            get {
                return ResourceManager.GetString("Expression_RightOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression contains unpaired square brackets. 的本地化字符串。
        /// </summary>
        internal static string Expression_UnpairedBracket {
            get {
                return ResourceManager.GetString("Expression_UnpairedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression contains unpaired text quotes. 的本地化字符串。
        /// </summary>
        internal static string Expression_UnpairedTextquotes {
            get {
                return ResourceManager.GetString("Expression_UnpairedTextquotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Division by zero. 的本地化字符串。
        /// </summary>
        internal static string Expression_ZeroDivision {
            get {
                return ResourceManager.GetString("Expression_ZeroDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将选中要素加入新图层 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Create_Layer_From_Selected_Features {
            get {
                return ResourceManager.GetString("FeatureLayer_Create_Layer_From_Selected_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join Excel file &apos;Data&apos; Label 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Join_Excel_File {
            get {
                return ResourceManager.GetString("FeatureLayer_Join_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签设置 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Label_Setup {
            get {
                return ResourceManager.GetString("FeatureLayer_Label_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Labeling {
            get {
                return ResourceManager.GetString("FeatureLayer_Labeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部选中 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_SelectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Selection {
            get {
                return ResourceManager.GetString("FeatureLayer_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选中 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_UnselectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到选中要素 的本地化字符串。
        /// </summary>
        internal static string FeatureLayer_Zoom_To_Selected {
            get {
                return ResourceManager.GetString("FeatureLayer_Zoom_To_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件 %S 不能被删除，可能被其他应用占用 的本地化字符串。
        /// </summary>
        internal static string FileCantBeDeletedException_S {
            get {
                return ResourceManager.GetString("FileCantBeDeletedException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string Layer_Properties {
            get {
                return ResourceManager.GetString("Layer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建分组 的本地化字符串。
        /// </summary>
        internal static string LayerFrame_CreateGroup {
            get {
                return ResourceManager.GetString("LayerFrame_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图图层 的本地化字符串。
        /// </summary>
        internal static string LayerFrame_Map_Layers {
            get {
                return ResourceManager.GetString("LayerFrame_Map_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除地图框架 的本地化字符串。
        /// </summary>
        internal static string LayerFrame_RemoveMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_RemoveMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到地图框架 的本地化字符串。
        /// </summary>
        internal static string LayerFrame_ZoomToMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_ZoomToMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型不支持 的本地化字符串。
        /// </summary>
        internal static string LayerManager_FileTypeNotSupported {
            get {
                return ResourceManager.GetString("LayerManager_FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是兼容的线数据类型 的本地化字符串。
        /// </summary>
        internal static string LineFeatureTypeException {
            get {
                return ResourceManager.GetString("LineFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 %S 不能为空 的本地化字符串。
        /// </summary>
        internal static string NullLogException_S {
            get {
                return ResourceManager.GetString("NullLogException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是兼容的点数据类型 的本地化字符串。
        /// </summary>
        internal static string PointFeatureTypeException {
            get {
                return ResourceManager.GetString("PointFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是兼容的面数据类型 的本地化字符串。
        /// </summary>
        internal static string PolygonFeatureTypeException {
            get {
                return ResourceManager.GetString("PolygonFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除图层 的本地化字符串。
        /// </summary>
        internal static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置动态可见比例尺 的本地化字符串。
        /// </summary>
        internal static string SetDynamicVisibilityScale {
            get {
                return ResourceManager.GetString("SetDynamicVisibilityScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到图层 的本地化字符串。
        /// </summary>
        internal static string ZoomToLayer {
            get {
                return ResourceManager.GetString("ZoomToLayer", resourceCulture);
            }
        }
    }
}
